force-app/main/default/objects/Board__c/Board__c.object-meta.xml
<CustomObject>
    <label>Board</label>
    <nameField>
        <label>Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Board_Updated__e/Board_Updated__e.object-meta.xml
<CustomObject>
    <label>Board Updated</label>
    <pluralLabel>Boards Updated</pluralLabel>
</CustomObject>

force-app/main/default/objects/Board_Updated__e/fields/Board_Id__c.field-meta.xml
<CustomField>
    <fullName>Board_Id__c</fullName>
    <label>Board Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BoardServiceTest.cls
@IsTest
private class BoardServiceTest {
    
    @IsTest
    private static void testBoardUpdateCallback() {
        Board__c b = new Board__c();
        insert b;
        Metadata.DeployCallback callback = new BoardService.BoardUpdateCallback(
            new EventBusService().add(new Board_Updated__e(Board_Id__c = b.Id))
        );
        Metadata.DeployResult result = new Metadata.DeployResult();
        result.status = Metadata.DeployStatus.Succeeded;
        result.details = new Metadata.DeployDetails();
        Metadata.DeployCallbackContext context = new Metadata.DeployCallbackContext();
        callback.handleResult(result, context);
    }
}